### PR TITLE
Create trello.json

### PR DESCRIPTION
**Pull request by HarshMN2345**
This pull request addresses Issue https://github.com/swirlai/swirl-search/issues/690 and introduces Trello as a new search provider in SwirlAI. With this enhancement, users will now be able to seamlessly integrate Trello boards into their search results, providing a more comprehensive and streamlined search experience.
Changes Made:
Implemented Trello API integration to fetch search results.
Added functionality to parse and display Trello cards within search results.
Enhanced user interface to accommodate Trello-specific information, such as board names and card details.
To run the trello provider add
"searchproviders": { "trello": { "type": "trello.TrelloSearchProvider", "api_key": "YOUR_API_KEY", "api_token": "YOUR_API_TOKEN", } }
to your Swirl Configuration file and restart Swirl and start searching for the Trello content.

### CODE REVIEW

**Review by sid-swirl — CHANGES_REQUESTED** [review]
Hi @HarshMN2345 ! Thank you so much for the contribution. It looks viable. Please see comments on this PR, which is the same as the one you submited: https://github.com/swirlai/swirl-search/pull/707

Thank you again!

**Comment by HarshMN2345** [comment]
@sid-swirl  done

**Comment by sid-swirl** [comment]
Hi @HarshMN2345 this is much closer. However, the result_mappings won't work bc they don't specify the required Swirl field names. 

```
id=id,fullName=fullName,username=username,email=email,url=url,avatarUrl=avatarUrl,avatarHash=avatarHash,memberType=memberType,status=status,initials=initials,products=products,idBoards=idBoards,idOrganizations=idOrganizations,limits=limits,prefs=prefs,trophies=trophies,uploadedAvatarHash=uploadedAvatarHash,uploadedAvatarUrl=uploadedAvatarUrl,premiumFeatures=premiumFeatures,isAaMastered=isAaMastered,ixUpdate=ixUpdate,idBoardsPinned=idBoardsPinned
```

The Swirl fields are url, title, body, author and date_published. So you should map those if the name isn't the same. You can combine fields using the | operator on the right hand side. So for example title=fullName or whatever field you want.

If you want to include a field (like trophies) that isn't in Swirl, just declare it without =

So it should look more like this:

```
        "result_mappings": "title=fullName,body=products,author=email,status,prefs,trophies,NO_PAYLOAD"
```

**Comment by HarshMN2345** [comment]
@sid-swirl i have done some changes as mentioned can you review it?

**Comment by HarshMN2345** [comment]
@sid-swirl  pls check whether there are any issues or is it good to go?

**Review by dnicodemus — APPROVED** [review]

**Comment by sid-swirl** [comment]
Hi @HarshMN2345 thank you for these updates. There are a few issues here 

* The authentication should be in the credentials field

* These result mappings likely won't work:

author=email | status | prefs | trophies
url=NO_PAYLOAD

Another Trello provider has been accepted and merged, please continue dev from there thank you!

**Comment by HarshMN2345** [comment]
thanks @sid-swirl for letting me know

**Pull request closed without merging**
