### PR TITLE
Add support for Ollama, Palm, Claude-2, Cohere, Replicate Llama2, CodeLlama, Hugging Face (100+LLMs) - using LiteLLM

### PR DESCRIPTION
**Pull request by ishaan-jaff**
This PR adds support for the above mentioned LLMs using LiteLLM https://github.com/BerriAI/litellm/ 
LiteLLM is a lightweight package to simplify LLM API calls - use any llm as a drop in replacement for gpt-3.5-turbo. 

Example
```python
from litellm import completion

## set ENV variables
os.environ["OPENAI_API_KEY"] = "openai key"
os.environ["COHERE_API_KEY"] = "cohere key"

messages = [{ "content": "Hello, how are you?","role": "user"}]

# openai call
response = completion(model="gpt-3.5-turbo", messages=messages)

# cohere call
response = completion(model="command-nightly", messages)

# anthropic call
response = completion(model="claude-instant-1", messages=messages)
```

### CODE REVIEW

**Comment by ishaan-jaff** [comment]
@dnicodemus @erikspears @sid-swirl can you take a look at this PR when possible ?

**Comment by sid-swirl** [comment]
Thanks so much will look later tonight!

**Comment by sid-swirl** [comment]
Hi @ishaan-jaff this is awesome. One proposed refactor: 

* Copy the chatgpt and chatgpt_query modules to new ones like microllm and microllm_query (or similar) and apply the changes

Happy to discuss; we would like retire or deprecate the old chatgpt ones and make these the default after testing etc. Thank you so much again for the contribution!

**Review by sid-swirl — CHANGES_REQUESTED** [review]
Hi @ishaan-jaff this is awesome. One proposed refactor... instead of modifying these modules, plz copy and apply changes in new ones like microllm and microllm_query (or similar). Happy to discuss; we would like retire or deprecate the old chatgpt ones and make these the default after testing etc. Thank you!!

**Comment by srbhr** [comment]
Hi @ishaan-jaff, thanks for the PR. Please check the [contributing](https://github.com/swirlai/swirl-search#-contributing-to-swirl) guidelines. You need to create a PR for the `develop` branch by branching out from the `develop` branch.

**Comment by sid-swirl** [comment]
Hi @ishaan-jaff again thanks for this. We're going to close this PR for now, we are going to adapt this ourselves, will ask for your review in a new PR soon!

**Pull request closed without merging**
