### PR TITLE
Search Provider : Yelp Search

### PR DESCRIPTION
**Pull request by Harshil0512**
Implemented Yelp Search Provider

## Related Issue(s)

Associated issue https://github.com/swirlai/swirl-search/issues/917

## Type of Change

- [ ] Bug fix or other non-breaking change that addresses an issue
- [x] New Feature / Enhancement (non-breaking change that add or improves functionality)
- [ ] New Feature (breaking change that is not backwards compatible and/or alters current functionality)
- [ ] Documentation (change to product documentation or README.md only)

### CODE REVIEW

**Review by erikspears — CHANGES_REQUESTED** [review]
And hello again, @Harshil0512 !  Thansk for this one as well...similar changes if you could please?
- Retarget this file to land in `SearchProviders/untested` on the `develop` branch
- Could you add some additional result_mappings?  We'd like to see at least mappings for Swirl's supported fields (`title`, `body`, `author`, `date_published`, and `url`) plus 
- Also, beware of the spaces in your `result_mappings` line

Much appreciated!

**Comment by Harshil0512** [comment]
> And hello again, @Harshil0512 ! Thansk for this one as well...similar changes if you could please?
> 
> * Retarget this file to land in `SearchProviders/untested` on the `develop` branch
> * Could you add some additional result_mappings?  We'd like to see at least mappings for Swirl's supported fields (`title`, `body`, `author`, `date_published`, and `url`) plus
> * Also, beware of the spaces in your `result_mappings` line
> * Do you need the `LenLimitingResultProcessor` based on the size of the response body from the source?
> 
> Much appreciated!

Hello @erikspears, Thank you for your response. I've performed the changes can you please have a look into it? I've removed `LenLimitingResultProcessor` as I'm limiting the response by query string only

**Review by erikspears — CHANGES_REQUESTED** [review]
Hi @Harshil0512 ,

Thanks for the updates.  This is getting close, but it doesn't look quite right yet to me. 
 Running your query + query_template in Postman, with an API key (finally! yelp took forever), I can see some things that won't work.

- Your `response_mappings` `RESULTS` value should be set to `businesses` ... that's the segment of the response that holds the individual results.  I don't see a `results` clause at all, curious where you got that?
- Similarly in `result_mappings`, I don't see a term to map Swirl's title to.  Maybe this is confusing, but these mappings are designed to map a Swirl field to a Source field.  So Swirl's `title` should probably be mapped to `name`, for a Yelp business search like this.  There is also a nice `url` field in the repsonse...why not map that to Swirl's url field?  And your mapping for `body` won't do as-is...you've got at mapped to the whole results list; instead select a speicfic field for that in the repsonse.

Thanks,
--Erik

**Comment by Harshil0512** [comment]
Hello @erikspears , 
Thank you for your response,
I did the mappings you've asked can you please validate it

Thanks again

**Review by erikspears — APPROVED** [review]

**Pull request merged**
