### PR TITLE
Search Provider Added : DuckDuckGo

### PR DESCRIPTION
**Pull request by Harshil0512**
Implemented DuckDuckGo Search

Now, you can start searching for DuckDuckGo Search content.

## Related Issue(s)

Associated issue https://github.com/swirlai/swirl-search/issues/897

## Type of Change

- [ ] Bug fix or other non-breaking change that addresses an issue
- [x] New Feature / Enhancement (non-breaking change that add or improves functionality)
- [ ] New Feature (breaking change that is not backwards compatible and/or alters current functionality)
- [ ] Documentation (change to product documentation or README.md only)

### CODE REVIEW

**Review by erikspears — CHANGES_REQUESTED** [review]
Hi @Harshil0512 ,
Thanks for this contribution as well!  Couple things to change please...
- Retarget this file to land in `SearchProviders/untested` on the `develop` branch
- Could you add some additional result_mappings?  We'd like to see at least mappings for Swirl's supported fields (`title`, `body`, `author`, `date_published`, and `url`) plus 
- Also, beware of the spaces in your `result_mappings` line

Thanks!

**Comment by Harshil0512** [comment]
> Hi @Harshil0512 , Thanks for this contribution as well! Couple things to change please...
> 
> * Retarget this file to land in `SearchProviders/untested` on the `develop` branch
> * Could you add some additional result_mappings?  We'd like to see at least mappings for Swirl's supported fields (`title`, `body`, `author`, `date_published`, and `url`) plus
> * Also, beware of the spaces in your `result_mappings` line
> 
> Thanks!

Hello @erikspears, Thank you for your response. I've performed the changes can you please have a look into it?

**Review by erikspears — CHANGES_REQUESTED** [review]
Hi @Harshil0512 , thanks for the update, getting closer!
Please consider the following...

- removing the `LenLimitingResultProcessor` as it doesn't look like you'd need it based on the length of the reponse fields (at leeast the ones I'm seeing)
- fix up the result_mappings:  keep in mind the format is SwirlField=ResponseField; so, for Swirl's `title` field, maybe DDG's `FirstURL` field makes sense (`title=FirstURL`), and Swirl's `body` field might be mapped nicely to DDG's `Result` or `Text` field, etc.
- If you need to dive into an array in the response, mind your syntax on that.  Check some of the existing SearchProviders for example.

Thanks again!
--Erik

**Comment by Harshil0512** [comment]
Hello @erikspears,
Thank you for your reply, I've performed all the changes you requested Please have a look into it

**Review by erikspears — APPROVED** [review]

**Review by erikspears — APPROVED** [review]

**Pull request merged**
