### PR TITLE
Create vespa.json

### PR DESCRIPTION
**Pull request by HarshMN2345**
Implemented Vespa Search
Associated issue https://github.com/swirlai/swirl-search/issues/692

To utilize this functionality, follow these steps:

Start Vespa Instance:
Ensure you have a running Vespa instance. If not, refer to Vespa's official documentation for installation instructions.

Add JSON File to Swirl Configuration:
Insert the provided JSON file into your Swirl configuration file.

Restart Swirl:
Restart Swirl to apply the changes.

Now, you can start searching for Vespa content. Use the following command:

swirl search vespa "my query"

### CODE REVIEW

**Comment by HarshMN2345** [comment]
@sidprobstein this is the new PR successor of approved PR #882

**Review by sidprobstein — APPROVED** [review]
Thanks @HarshMN2345 looks good, approved

**Comment by HarshMN2345** [comment]
hey @sidprobstein can i be merged ?

**Comment by HarshMN2345** [comment]
hi @dnicodemus can it be merged?

**Review by erikspears — APPROVED** [review]

**Pull request merged**
