### PR TITLE
Updated readme with larger logo and add overview.

### PR DESCRIPTION
**Pull request by srbhr**
Hi Swirl team. This PR adds:
- Better Readme Title with breathing space while reading.
- Adds some quick links to get started (quickly).

This is what it looks like:
image

Feel free to comment and suggest changes if needed.

### CODE REVIEW

**Review by dnicodemus — CHANGES_REQUESTED** [review]
Hi Saurabh,


Thanks for the submission. Overall, some great ideas, but we don't want to repeat the entire public repo Readme. Can you make this a short Readme that directs users to the public repo?

Thanks again,
Dave

**Comment by srbhr** [comment]
Okay!
 @dnicodemus, May I ask where I should put a short Readme?
 E.g. Are you looking at something like this: https://github.com/prisma
 Prisma (Company) has a Readme Prisma/Readme.md which contains links to their platform etc.
 And then https://github.com/prisma/prisma has it's own readme as well.

**Comment by dnicodemus** [comment]
Hi @srbhr, Good morning.

The placement of the file is good, we’re just looking for the content to be more succinct,  and  to point people to the repos page.

Thanks
DaveN

**Comment by srbhr** [comment]
@dnicodemus I've updated the PR (by amending commits). Let me know your merge strategy as well for SWIRL. And please suggest any changes.

**Pull request closed without merging**
