### PR TITLE
feat: Qdrant search provider

### PR DESCRIPTION
**Pull request by Anush008**
## Description
This PR adds a search provider implementation using Qdrant - https://qdrant.tech./.

I noticed Qdrant is mentioned in the docs at https://github.com/swirlai/swirl-search/blob/main/docs/index.md#what-systems-can-swirl-ai-connect-integrate-with

However, the implementation was not present.

## Notes

- The URL is to be passed as
 `QDRANT_URL-COLLECTION-NAME`

Eg: `http://localhost:6333-my_collection`

- To start Qdrant 

```
docker run -p 6333:6333 qdrant/qdrant
```

- To create a collection, refer to https://qdrant.tech/documentation/concepts/collections/#create-a-collection.

- To add points, refer to https://qdrant.tech/documentation/concepts/points/#upload-points

- There'll also be a dashboard at http://localhost:6333/dashboard

### CODE REVIEW

**Comment by sid-swirl** [comment]
Thanks @Anush008!! I am looking at this now.

**Comment by Anush008** [comment]
Hi @sid-swirl, thank you. I've added some notes that might come in handy.

**Comment by sid-swirl** [comment]
Works great!
image (24)

**Comment by sid-swirl** [comment]
This will be merged later today

**Review by sid-swirl — APPROVED** [review]
Excellent work! Here's an updated SP: 

`{
    "name": "QdrantDB",
    "active": true,
    "default": false,
    "authenticator": "",
    "connector": "QdrantDB",
    "url": "http://localhost:6333/-qdrant_doc",
    "query_template": "",
    "query_template_json": {},
    "post_query_template": {},
    "http_request_headers": {},
    "page_fetch_config_json": {},
    "query_processors": [
        "AdaptiveQueryProcessor"
    ],
    "query_mappings": "",
    "result_grouping_field": "",
    "result_processors": [
        "MappingResultProcessor",
        "AutomaticPayloadMapperResultProcessor",
        "CosineRelevancyResultProcessor"
    ],
    "response_mappings": "",
    "result_mappings": "",
    "results_per_query": 10,
    "credentials": "",
    "eval_credentials": "",
    "tags": [
        "Qdrant",
        "model:sentence-transformers/all-MiniLM-L6-v2"
    ]
}`

**Pull request merged**
