### PR TITLE
Remove Snowflake AI connector, init, model, SP

### PR DESCRIPTION
**Pull request by sid-swirl**
## Branching Reminders
X For core code changes, create a branch off `develop`
- For product documentation changes, create a branch off `main` 
- Always name your branch in a way that clearly describes your proposed changes

## Description

Remove SnowflakeAI connector, connector/init, SP, model

## Related Issue(s)

DS-1842

## Testing and Validation

Tested other SPs

## Type of Change

- [X] Bug fix or other non-breaking change that addresses an issue
- [ ] New Feature / Enhancement (non-breaking change that add or improves functionality)
- [ ] New Feature (breaking change that is not backwards compatible and/or alters current functionality)
- [ ] Documentation (change to product documentation or README.md only)

### CODE REVIEW

**Review by dnicodemus — CHANGES_REQUESTED** [review]
Can you also remove snowflake-connector-python from requirements.txt? I don't believe it's used anywhere either.

**Comment by sid-swirl** [comment]
Removed !

**Review by dnicodemus — CHANGES_REQUESTED** [review]
Sorry one more thing, can you check the SearchProviders/preload.json There is a snowflake provider in there does it need to be removed?

**Review by erikspears — COMMENTED** [review]
@dnicodemus , no issue with your last question, prealoaded.json is all set as-is.  Running smoke tests on the branch now (after merging develop in to update it); if they pass, I'll merge this and let the full suite run.

**Review by erikspears — APPROVED** [review]

**Review by dnicodemus — APPROVED** [review]

**Pull request merged**
