### PR TITLE
Create trello.json

### PR DESCRIPTION
**Pull request by neelshah2409**
## Implemented Trello Search Provider 
- Issue associated : #690 
- To run the trello provider add 
 `"searchproviders": {
    "trello": {
        "type": "trello.TrelloSearchProvider",
        "api_key": "YOUR_API_KEY",
        "api_token": "YOUR_API_TOKEN",
    }
}`
to your Swirl Configuration file and restart Swirl and start searching for the Trello content.

### CODE REVIEW

**Review by sid-swirl — CHANGES_REQUESTED** [review]
Hi @neelshah2409 !! Thank you for this, it looks viable. However, there is no need to manually make the request in code. Instead, make a json SearchProvider based on one of the ones here: https://github.com/swirlai/swirl-search/blob/main/SearchProviders/google_pse.json 

It should use the RequestsGet connector. Move the url and authentication into the appropriate sections, as strings/configuration - not code. 

For example:

```
{
        "name": "Trello",
        "active": true,
        "default": true,
        "connector": "RequestsGet",
        "url": "https://api.trello.com/1"",
        "query_template": "{url}?q={query_string}",
        "query_processors": [
            "AdaptiveQueryProcessor"
        ],
        "query_mappings": "",
        "result_processors": [
            "MappingResultProcessor",
            "CosineRelevancyResultProcessor"
        ],
        "response_mappings": "RESULTS=cards",
        "result_mappings": "title=name,body=desc",
        "credentials": "bearer=<your-trello-token>,
        "tags": [
            "Trello"
        ]
    }
 ```

Suggest reverting your changes to __init__.py and models.py. Once you have trello.json looking like the above load it as described here: https://github.com/swirlai/swirl-search/wiki/2.-User-Guide#copypaste-install

You should be able to try it immediately, e.g.

`localhost:8000/swirl/search/?q=trello:some+query`

**Comment by sid-swirl** [comment]
Hi @neelshah2409 please change the PR to target the develop branch, per the contribution guidelines. Otherwise, this is good to go! Thank you.

**Comment by neelshah2409** [comment]
Hey @sid-swirl  could you help me out to directly shift this to develop as I was doing it showed 243 previous commits pending so what should I do.

**Comment by sid-swirl** [comment]
> Hey @sid-swirl could you help me out to directly shift this to develop as I was doing it showed 243 previous commits pending so what should I do.

That's ok, but the branch has to be develop. I'll pull/update before approving. If you switch it back to develop, this should be good to go.

**Comment by neelshah2409** [comment]
@sid-swirl Done , thank you 😁

**Comment by neelshah2409** [comment]
Hey @sid-swirl ,have you checked it .

**Comment by neelshah2409** [comment]
@sid-swirl Please review this

**Pull request closed without merging**
