### PR TITLE
Added SearchProvider for Algolia 

### PR DESCRIPTION
**Pull request by Yash-sudo-web**
Addresses Issue #688

### CODE REVIEW

**Comment by Yash-sudo-web** [comment]
I have updated the PR according to the contributing guidelines.

**Review by sid-swirl — CHANGES_REQUESTED** [review]
Hi @Yash-sudo-web this looks great and viable. I suggest changing from RequestsPost to RequestsGet? The documentation is here: https://www.algolia.com/doc/rest-api/search/#search-index-get

**Comment by Yash-sudo-web** [comment]
hey @sid-swirl, i have changed the SearchProvider to handle Get requests instead, let me know if there are still any errors

**Comment by sid-swirl** [comment]
Excellent! Last point remove active and default, or set them to True, otherwise they will not run without changing. Make that change and this PR is ready to go

**Comment by Yash-sudo-web** [comment]
hello, its done

**Review by dnicodemus — APPROVED** [review]

**Pull request merged**
