### PR TITLE
Feature : Added SearchProvider for Algolia

### PR DESCRIPTION
**Pull request by Yash-sudo-web**
Addresses Issue #688

### CODE REVIEW

**Comment by dnicodemus** [comment]
Thanks for the contribution @Yash-sudo-web Did you test this with Swirl?

**Comment by Yash-sudo-web** [comment]
Hey @dnicodemus, unfortunately, Swirl isn't supported for local installation or production on Windows, so I couldn't run it locally. However, I've thoroughly tested and validated the changes. Let me know if there's anything specific you'd like me to address or if you have any suggestions for a workaround. Thanks!

**Comment by erikspears** [comment]
Hi @Yash-sudo-web , correct on the local use of Windows.  However, Swirl's Docker does run in Windows, and as you're change is new SearchProvider (vs. core code), you should be able to add it and test drive it via Docker.  Just remember that our docker does not persist any data on shutdown, so if you make changes to the SP config in Docker, be sure to copy them out somewhere if you need to preseve them.

Guidance for running Swirl in Docker (including on Windows):  https://github.com/swirlai/swirl-search/wiki/1.-Quick-Start#docker-installation

**Comment by Yash-sudo-web** [comment]
thanks @erikspears, I'll test the same and let you know

**Comment by srbhr** [comment]
Hi @Yash-sudo-web, thanks for the PR. Please check the [contributing](https://github.com/swirlai/swirl-search#-contributing-to-swirl) guidelines. You need to create a PR to the develop branch by branching out from the develop branch.

**Comment by Yash-sudo-web** [comment]
Hey, sorry for the ignorance, I'll be closing this PR and create a new one following the contributing guidelines.

**Pull request closed without merging**
