### PR TITLE
Added Asana SearchProvider

### PR DESCRIPTION
**Pull request by LunarMarathon**
Closes: #687 
I'm not sure if it's right, please review.

### CODE REVIEW

**Comment by srbhr** [comment]
Hi @LunarMarathon, thanks for the PR. Please check the [contributing](https://github.com/swirlai/swirl-search#-contributing-to-swirl) guidelines. You need to create a PR to the `develop` branch by branching out from the `develop` branch. 
Also, join in the [Slack](https://join.slack.com/t/swirlmetasearch/shared_invite/zt-1qk7q02eo-kpqFAbiZJGOdqgYVvR1sfw) for any discussion.

**Review by sid-swirl — CHANGES_REQUESTED** [review]
This is excellent @LunarMarathon !! Please target the develop branch, otherwise this looks viable. Have you tested against a live Asana? Thank you!

**Comment by mathagician** [comment]
I want to work on this if it is still open. Please let me know.

**Review by sidprobstein — CHANGES_REQUESTED** [review]
Please target swirlai:develop per the guidelines and this is good to go. Thank you!

https://github.com/swirlai/swirl-search#-contributing-to-swirl

**Review by erikspears — COMMENTED** [review]
Hi @LunarMarathon , in addition to Sid's comment on landing this PR on our `develop` branch (not `main`), please also target it to land in the SearchProviders/untested directory of develop.  Thank you!

**Comment by erikspears** [comment]
Closing this out.  We'll be shipping an Asana SP in Swirl 3.1.0.

**Pull request closed without merging**
