### PR TITLE
Update trello.json

### PR DESCRIPTION
**Pull request by HarshMN2345**
Added author, date_published, and url to the result_mappings.

### CODE REVIEW

**Review by sidprobstein — APPROVED** [review]
Looks good thanks @HarshMN2345

**Comment by HarshMN2345** [comment]
hey @sidprobstein can it be merged?

**Comment by HarshMN2345** [comment]
hi @dnicodemus can this be merged?

**Review by erikspears — CHANGES_REQUESTED** [review]
Hi @HarshMN2345 ,

Your trello.json lives in our SearchProviders/untested directory.  Could you please retarget these updates to land there, so that we're merging the updates into the existing JSON file?  You can see it here:  https://github.com/swirlai/swirl-search/tree/develop/SearchProviders/untested

Thanks!

**Comment by HarshMN2345** [comment]
@erikspears sure

**Review by erikspears — CHANGES_REQUESTED** [review]
@HarshMN2345 , please take another look?  Maybe pull develop or merge it into your local branch to make sure you're up to date first.

Your original trello.json file was already merged, we don't need the full file again.  That file lives in the repo under SearchProviders/untested

The original fix in result_mappings should be made to that existing file. 

Does that help clarify things?

Thanks,
--Erik

**Comment by HarshMN2345** [comment]
@erikspears done the changes please resolve conflicts

**Comment by HarshMN2345** [comment]
@erikspears okay adding another PR

**Pull request closed without merging**
