### PR TITLE
Implemented Internet Archive Search Provider

### PR DESCRIPTION
**Pull request by Janvi-Thakkar**
**Implemented Archive Search Provider**

## Related Issue(s)
https://github.com/swirlai/swirl-search/issues/931

## Type of Change

- [ ] Bug fix or other non-breaking change that addresses an issue
- [x] New Feature / Enhancement (non-breaking change that add or improves functionality)
- [ ] New Feature (breaking change that is not backwards compatible and/or alters current functionality)
- [ ] Documentation (change to product documentation or README.md only)**

### CODE REVIEW

**Review by erikspears — COMMENTED** [review]
Hi @Janvi-Thakkar , 
Thank you for the PR!  Your PR title is:  `Implemented Internet Explorer Search Provider`

Did you mean "Internet Archive" vs. the old Windows web browser?  :)

**Review by erikspears — CHANGES_REQUESTED** [review]
Hi @Janvi-Thakkar ,
Thanks for the contribution!  Could you please make a few changes...
- Fix the title of the PR? :) 
- Do you need the `LenLimitingResultProcessor` based on the size of the response body from the source?
- Please provider additional result_mappings; we like to see mappings for Swirl's supported fields (`title`, `body`, `author`, `date_published`, and `url`) at minimum. 

Thanks!

**Comment by Janvi-Thakkar** [comment]
> Hi @Janvi-Thakkar , Thanks for the contribution! Could you please make a few changes...
> 
> * Fix the title of the PR? :)
> * Do you need the `LenLimitingResultProcessor` based on the size of the response body from the source?
> * Please provider additional result_mappings; we like to see mappings for Swirl's supported fields (`title`, `body`, `author`, `date_published`, and `url`) at minimum.
> 
> Thanks!

Hello @erikspears, Thank you for reviewing the PR. I will make the suggested changes.

**Comment by Janvi-Thakkar** [comment]
Hello @erikspears, Updated the code as per your suggestions. Also, removed **LenLimitingResultProcessor** as the number of results can be managed using queryString. Thank you for your patience:)

**Review by erikspears — CHANGES_REQUESTED** [review]
Hi @Janvi-Thakkar , thanks for making those change...getting close.  :)
I'd recommend the following...

- add all the fields you have in query_template to the url field instead; so, your query_template value would be something simple like `{url}q={query_string}` and everything else would be in the `url` field
- fix your response_mappings:  something more like `FOUND=total,RESULTS=item` ...take a look at a full response in Postman or the like to see why (scroll allll the way to the bottom too, that's often where the result count hides)
- Update your result_mappings:  remember that the format is SwirlField = ResponseField.  So Swirl's `title` in this case maps to archive.org's `title` field (`title=title`); but the Swirl's `body` field could nicely map to their `description` field (`body=description`).  Please check the others, I can see some good candidates in the response data.  :) 

Thanks again!
--Erik

**Comment by erikspears** [comment]
Unfortunately we cannot this PR.  Closing it out

**Pull request closed without merging**
